- name: Harden sshd configuration
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
    state: present
  with_items:
  - regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
  - regexp: "^^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
  - regexp: "^#?AllowAgentForwarding"
    line: "AllowAgentForwarding no"
  - regexp: "^#?MaxAuthTries"
    line: "MaxAuthTries 2"
  - regexp: "^#?MaxSessions"
    line: "MaxSessions 2"
  - regexp: "^#?TCPKeepAlive"
    line: "TCPKeepAlive no"
  - regexp: "^#?UseDNS"
    line: "UseDNS no"
  - regexp: "^#?AllowAgentForwarding"
    line: "AllowAgentForwarding no"

- name: allow ubuntu user to be sudo without pass
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%ubuntu\s'
    line: '%ubuntu ALL=(ALL) NOPASSWD: ALL'

- name: Restart sshd
  systemd:
    state: restarted
    daemon_reload: yes
    name: sshd